verify tagging in release, tighten up global perms

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -65,6 +65,14 @@ jobs:
         # verify version
         just verify_version $TAG_NAME
 
+        # check that github has marked the tag as verified
+        export TAG_URL=`curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/git/refs/tags/$TAG_NAME | jq -r ".object.url"`
+        result=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$TAG_URL" | jq -r ".verification.verified")
+        if [ "$result" != "true" ]; then
+          echo "Error: Tag verification failed." >&2
+          exit 1
+        fi
+
         # export the release version
         echo "RELEASE_VERSION=${TAG_NAME}" >> $GITHUB_ENV 
     - name: Build the binary wheel and a source tarball
